version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: incomer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: incomer_user
      POSTGRES_PASSWORD: incomer_pass
      POSTGRES_DB: incomer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: incomer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: